spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_SERVER_URL}/realms/${KEYCLOAK_REALM}

server:
  port: ${SERVER_PORT}

#app:
#  cors:
#    allowed-origins:
#      - ${CHAT_SERVICE_URL}

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  admin-cli:
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
    username: ${KEYCLOAK_ADMIN_USERNAME}
    password: ${KEYCLOAK_ADMIN_PASSWORD}

mail:
  internal:
    domain: ${INTERNAL_MAIL_DOMAIN:gitlab.handbook.local}
    api-url: ${MAIL_ACCOUNT_API_URL:http://mail-account-manager:8080}
    webmail-url: ${WEBMAIL_URL:http://localhost:8085/}
    quota-bytes: ${MAILBOX_QUOTA_BYTES:104857600}
